name: Publish

on:
  release:
    types: [published, prereleased]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CARGO_REGISTRY_TOKEN: ${{ env.CRATES_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: cargo build --verbose
      - name: Publish
        run: cargo publish --config package.version=${{ env.RELEASE_VERSION }}